---
- hosts: 192.168.10.180
  gather_facts: false
  connection: local

  tasks:
    - name: Debug message
      debug:
        msg: "hello world"

    - name: run show version on remote devices
      ios_command:
        commands: show version